[build.environment]
  NPM_FLAGS = "--version" # prevents Netlify npm install
  NODE_VERSION = "16"

[build]
  publish = "apps/web/dist"
  command = "npx pnpm install --store=node_modules/.pnpm-store && npx pnpm build"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200