name: CD Preview

on:
  pull_request:
    branches:
      - main

env:
  HEAD_REF: ${{ github.head_ref }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy server preview on VPS
        uses: appleboy/ssh-action@master
        with:
          envs: HEAD_REF
          host: ${{secrets.HOST}}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd apps/enis2-server-preview
            echo $HEAD_REF
            git checkout $HEAD_REF
            git status
            npx pnpm install --filter api --store=node_modules/.pnpm-store
            # npx pm2 restart enis2-server-preview –silent
