name: CD Production

on:
  pull_request:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy server on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd apps/enis2
            git fetch
            git reset --hard origin/main
            npx pnpm install --filter api --store=node_modules/.pnpm-store
            npx pm2 restart enis2
