name: Deploy dev server

on:
  push:
    branches:
      - master

  workflow_dispatch:

env:
  REF: ${{ github.ref }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy dev server on VPS
        uses: appleboy/ssh-action@master
        with:
          envs: REF
          host: ${{secrets.HOST}}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd apps/enis2-dev
            echo $REF
            git checkout $REF
            git status
            npx pnpm install --filter api --store=node_modules/.pnpm-store
            npx pm2 restart enis2-dev -silent
